$(function(){
	$('.sec-15').click(function(){
		$($(".section")[0]).css({
			'background-image':'url(img/banner_mac.jpg)'
		});
//		console.log($(".sec-6"));
		$($(".sec-6")[0]).hide()
		$($(".sec-11")[0]).hide()	
		$($(".sec-a")[0]).hide()
		$($('.sec-8')[0]).hide()
		$($('.sec-q')[0]).toggle()
		$($('.sec-w')[0]).hide()
		$($('.sec-e')[0]).hide()
	})
	$('.sec-16').click(function(){
//		console.log($(".section")[0]);
		$($(".section")[0]).css({
			'background-image':'url(img/iphone_play_1.jpg)'
		});
		$($(".sec-6")[0]).hide()
		$($(".sec-11")[0]).hide()	
		$($(".sec-a")[0]).hide()	
		$($('.sec-8')[0]).hide()
		$($('.sec-q')[0]).hide()
		$($('.sec-w')[0]).toggle()
		$($('.sec-e')[0]).hide()
	})
	$('.sec-17').click(function(){
		console.log($(".section")[0]);
		$($(".section")[0]).css({
			'background-image':'url(img/banner_android.jpg)'
		});
		$($(".sec-6")[0]).hide()
		$($(".sec-11")[0]).hide()	
		$($(".sec-a")[0]).hide()	
		$($('.sec-8')[0]).hide()
		$($('.sec-q')[0]).hide()
		$($('.sec-w')[0]).hide()
		$($('.sec-e')[0]).toggle()
	})
	$('.sec-14').click(function(){
		console.log($(".section")[0]);
		$($(".section")[0]).css({
			'background-image':'url(img/banner_pc.jpg)'
		});
		$($(".sec-6")[0]).toggle()
		$($(".sec-11")[0]).toggle()	
		$($(".sec-a")[0]).toggle()	
		$($('.sec-8')[0]).toggle()
		$($('.sec-q')[0]).hide()
		$($('.sec-w')[0]).hide()
		$($('.sec-e')[0]).hide()
	})
	
})
